kind: pipeline
name: default

trigger:
  event:
    - push

services:
  - name: vault
    image: vault:1.5.3
    ports:
      - 8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
  - name: mysql
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: "kaigara_dev"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  - name: postgres
    image: postgres:13.3-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: kaigara_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme

steps:
  - name: Enable Vault Transit
    image: vault:1.5.3
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root-token"
    commands:
      - vault secrets enable transit

  - name: Go test
    image: golang:1.16
    environment:
      GO111MODULE: "on"
      KAIGARA_VAULT_ADDR: "http://vault:8200"
      KAIGARA_VAULT_TOKEN: "root-token"
      KAIGARA_APP_NAME: finex,frontdex,gotrue,postgrest,realtime,storage
      KAIGARA_DEPLOYMENT_ID: opendax_uat
      KAIGARA_SCOPES: public,private,secret
      KAIGARA_ENCRYPTION_METHOD: transit
      KAIGARA_AES_KEY: changeme
      DATABASE_HOST: "mysql"
      DATABASE_PORT: 3306
      DATABASE_POOL: 1
    commands:
      - go mod download
      - go test ./...

  - name: Bump and tag
    image: golang:1.14
    environment:
      GITHUB_API_KEY:
        from_secret: github_api_key
      GITHUB_API_USER:
        from_secret: github_api_user
    commands:
      - go get github.com/guilhem/bump
      - git remote add authenticated-origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/$DRONE_REPO
      - git fetch --tags authenticated-origin
      - bump patch --allow-dirty
      - git push authenticated-origin --tags
    when:
      branch:
        - master

---
kind: pipeline
name: publish

trigger:
  event:
    - tag

steps:
  - name: Build and publish
    image: golang:1.16
    environment:
      GO111MODULE: on
      GITHUB_API_KEY:
        from_secret: github_api_key
    commands:
      - go mod download
      - make build
      - go get github.com/tcnksm/ghr
      - ghr -t $GITHUB_API_KEY -u ${DRONE_REPO_NAMESPACE} -r ${DRONE_REPO_NAME} -c ${DRONE_COMMIT} -delete ${DRONE_TAG} ./bin
