kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

services:
  - name: vault
    image: vault:1.5.3
    ports:
      - 8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"

  - name: mysql
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: "kaigara_opendax_uat"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  - name: postgres
    image: postgres:13.3-alpine
    ports:
      - 5432
    command:
      - postgres
      - -c
      - wal_level=logical
      - -N 500
    environment:
      POSTGRES_DB: kaigara_opendax_uat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme

steps:
  - name: Wait for services
    image: jwilder/dockerize
    pull: if-not-exists
    commands:
      - dockerize -wait tcp://postgres:5432 -wait tcp://mysql:3306 -wait tcp://vault:8200 -timeout 2m

  - name: Enable Vault Transit
    image: vault:1.5.3
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root-token"
    commands:
      - vault secrets enable transit

  - name: Restore lint cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
    - name: golint-cache
      path: /golint-cache
    settings:
      restore: true
      mount:
      - .cache/golangci-lint
    when:
      branch:
        exclude:
          - "master"
          - "*stable"

  - name: Go lint
    image: golangci/golangci-lint:v1.49-alpine
    environment:
      GOLANGCI_LINT_CACHE: "/drone/src/.cache/golangci-lint"
    commands:
      - golangci-lint cache status
      - golangci-lint run --timeout 3m0s
    when:
      branch:
        exclude:
          - "master"
          - "*stable"

  - name: Rebuild lint cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
    - name: golint-cache
      path: /golint-cache
    settings:
      rebuild: true
      mount:
      - .cache/golangci-lint
    when:
      branch:
        exclude:
          - "master"
          - "*stable"

  - name: Go test
    image: golang:1.18
    environment:
      GO111MODULE: "on"
      KAIGARA_VAULT_ADDR: "http://vault:8200"
      KAIGARA_VAULT_TOKEN: "root-token"
      KAIGARA_DATABASE_HOST: "postgres"
    commands:
      - |
        for gpath in $(find $PWD -name go.mod); do cd $(dirname $gpath);
          for dir in $(go list ./...); do
            go clean -testcache;
            go test $dir;
          done;
        done

  - name: Bump and tag
    image: golang:1.18
    environment:
      GITHUB_API_KEY:
        from_secret: github_api_key
      GITHUB_API_USER:
        from_secret: github_api_user
    commands:
      - go install github.com/guilhem/bump@v0.2.1
      - git remote add authenticated-origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/$DRONE_REPO
      - git fetch --tags authenticated-origin
      - bump patch --allow-dirty
      - git push authenticated-origin --tags
    when:
      branch:
        - master

---
kind: pipeline
type: docker
name: publish

trigger:
  event:
    - tag

steps:
  - name: Build and publish
    image: golang:1.18
    environment:
      GO111MODULE: on
      GITHUB_API_KEY:
        from_secret: github_api_key
    commands:
      - echo $DRONE_TAG | grep -v / || exit 78 # Skip if submodule is tagged
      - go mod download
      - KAIGARA_VERSION=${DRONE_TAG} make build
      - go install github.com/tcnksm/ghr@v0.15.0
      - ghr -t $GITHUB_API_KEY -u ${DRONE_REPO_NAMESPACE} -r ${DRONE_REPO_NAME} -c ${DRONE_COMMIT} -delete ${DRONE_TAG} ./bin
