version: '3'
services:
  vault:
    image: hashicorp/vault:1.13
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "kaigara_opendax_uat"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: supabase/postgres:13.3.0
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -N 500
    environment:
      POSTGRES_DB: kaigara_opendax_uat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_PORT: "5432"
