version: '3'
services:
  redis:
    image: "redis:5-alpine"
    ports:
      - "6379:6379"

  vault:
    image: vault:0.11.4
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "kaigara_dev"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: supabase/postgres:13.3.0
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: kaigara_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_PORT: "5432"
